version: '3.0'
services:
  inobstudios-frontend:
    image: ghcr.io/sh1nku/inobstudios-frontend:${DOCKER_TAG}
    ports:
      - ${DOCKER_EXPOSED_PORT}:3000
    restart: unless-stopped
    environment:
      - VITE_API_SERVER=${VITE_API_SERVER}
      - VITE_HOSTNAME=${VITE_HOSTNAME}
